spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/HCSKS?serverTimezone=UTC
  redis:
    host: 127.0.0.1
    port: 26379
    password: 123456
    database: 0
    lettuce:
      pool:
        #???????
        max-active: 20
        #???????
        max-idle: 20
        #???????
        min-idle: 20

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
